// Generated by scripts/gen-db-types.mjs — do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      activities: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string;
          activity_type: "prospect_created" | "prospect_updated" | "note" | "stage_change" | "outreach_sent" | "response_recorded" | "task_created" | "task_completed" | "task_rescheduled" | "task_cancelled" | "qualification" | "handoff" | "opportunity" | "client" | "project" | "payment" | "archived" | "restored";
          title: string;
          details: string | null;
          metadata: Json;
          occurred_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id: string;
          activity_type: "prospect_created" | "prospect_updated" | "note" | "stage_change" | "outreach_sent" | "response_recorded" | "task_created" | "task_completed" | "task_rescheduled" | "task_cancelled" | "qualification" | "handoff" | "opportunity" | "client" | "project" | "payment" | "archived" | "restored";
          title: string;
          details?: string | null;
          metadata?: Json;
          occurred_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string;
          activity_type?: "prospect_created" | "prospect_updated" | "note" | "stage_change" | "outreach_sent" | "response_recorded" | "task_created" | "task_completed" | "task_rescheduled" | "task_cancelled" | "qualification" | "handoff" | "opportunity" | "client" | "project" | "payment" | "archived" | "restored";
          title?: string;
          details?: string | null;
          metadata?: Json;
          occurred_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "activities_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
        ];
      };
      clients: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string | null;
          company: string;
          primary_contact: string | null;
          email: string | null;
          phone: string | null;
          website: string | null;
          industry: string | null;
          location: string | null;
          notes: string | null;
          status: "active" | "inactive" | "past_client" | "nurture";
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id?: string | null;
          company: string;
          primary_contact?: string | null;
          email?: string | null;
          phone?: string | null;
          website?: string | null;
          industry?: string | null;
          location?: string | null;
          notes?: string | null;
          status?: "active" | "inactive" | "past_client" | "nurture";
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string | null;
          company?: string;
          primary_contact?: string | null;
          email?: string | null;
          phone?: string | null;
          website?: string | null;
          industry?: string | null;
          location?: string | null;
          notes?: string | null;
          status?: "active" | "inactive" | "past_client" | "nurture";
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "clients_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: true;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
        ];
      };
      handoffs: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string;
          qualification_id: string | null;
          status: "draft" | "sent" | "accepted" | "declined";
          summary_markdown: string;
          snapshot: Json;
          sent_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          opportunity_id: string | null;
          partner_id: string | null;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id: string;
          qualification_id?: string | null;
          status?: "draft" | "sent" | "accepted" | "declined";
          summary_markdown: string;
          snapshot?: Json;
          sent_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          opportunity_id?: string | null;
          partner_id?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string;
          qualification_id?: string | null;
          status?: "draft" | "sent" | "accepted" | "declined";
          summary_markdown?: string;
          snapshot?: Json;
          sent_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          opportunity_id?: string | null;
          partner_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "handoffs_opportunity_id_fkey";
            columns: ["opportunity_id"];
            isOneToOne: false;
            referencedRelation: "opportunities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "handoffs_partner_id_fkey";
            columns: ["partner_id"];
            isOneToOne: false;
            referencedRelation: "partners";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "handoffs_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "handoffs_qualification_id_fkey";
            columns: ["qualification_id"];
            isOneToOne: false;
            referencedRelation: "qualification_assessments";
            referencedColumns: ["id"];
          },
        ];
      };
      lookup_values: {
        Row: {
          id: string;
          owner_id: string;
          kind: "lead_source" | "industry" | "service_category";
          value: string;
          label: string;
          sort_order: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          kind: "lead_source" | "industry" | "service_category";
          value: string;
          label: string;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          kind?: "lead_source" | "industry" | "service_category";
          value?: string;
          label?: string;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      opportunities: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string;
          title: string;
          project_type: string | null;
          status: "open" | "won" | "lost";
          estimated_value: number | null;
          expected_close_date: string | null;
          closed_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          pipeline_id: string;
          stage_id: string;
          service_id: string | null;
          partner_id: string | null;
          description: string | null;
          probability: number | null;
          delivery_model: "self_delivered" | "partner_delivered" | "referral" | "white_label" | "joint_delivery" | null;
          next_action: string | null;
          next_action_date: string | null;
          lost_reason: string | null;
          stage_changed_at: string;
          revenue_model: "direct_revenue" | "referral_commission" | "partner_commission" | "revenue_share" | "fixed_fee" | "other" | null;
          commission_type: "none" | "percentage" | "fixed" | null;
          commission_percentage: number | null;
          fixed_commission: number | null;
          commission_basis: "total_project_value" | "amount_received" | "net_revenue" | "custom" | null;
          commission_notes: string | null;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id: string;
          title: string;
          project_type?: string | null;
          status?: "open" | "won" | "lost";
          estimated_value?: number | string | null;
          expected_close_date?: string | null;
          closed_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          pipeline_id: string;
          stage_id: string;
          service_id?: string | null;
          partner_id?: string | null;
          description?: string | null;
          probability?: number | null;
          delivery_model?: "self_delivered" | "partner_delivered" | "referral" | "white_label" | "joint_delivery" | null;
          next_action?: string | null;
          next_action_date?: string | null;
          lost_reason?: string | null;
          stage_changed_at?: string;
          revenue_model?: "direct_revenue" | "referral_commission" | "partner_commission" | "revenue_share" | "fixed_fee" | "other" | null;
          commission_type?: "none" | "percentage" | "fixed" | null;
          commission_percentage?: number | string | null;
          fixed_commission?: number | string | null;
          commission_basis?: "total_project_value" | "amount_received" | "net_revenue" | "custom" | null;
          commission_notes?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string;
          title?: string;
          project_type?: string | null;
          status?: "open" | "won" | "lost";
          estimated_value?: number | string | null;
          expected_close_date?: string | null;
          closed_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          pipeline_id?: string;
          stage_id?: string;
          service_id?: string | null;
          partner_id?: string | null;
          description?: string | null;
          probability?: number | null;
          delivery_model?: "self_delivered" | "partner_delivered" | "referral" | "white_label" | "joint_delivery" | null;
          next_action?: string | null;
          next_action_date?: string | null;
          lost_reason?: string | null;
          stage_changed_at?: string;
          revenue_model?: "direct_revenue" | "referral_commission" | "partner_commission" | "revenue_share" | "fixed_fee" | "other" | null;
          commission_type?: "none" | "percentage" | "fixed" | null;
          commission_percentage?: number | string | null;
          fixed_commission?: number | string | null;
          commission_basis?: "total_project_value" | "amount_received" | "net_revenue" | "custom" | null;
          commission_notes?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "opportunities_partner_id_fkey";
            columns: ["partner_id"];
            isOneToOne: false;
            referencedRelation: "partners";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "opportunities_pipeline_id_fkey";
            columns: ["pipeline_id"];
            isOneToOne: false;
            referencedRelation: "pipelines";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "opportunities_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "opportunities_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "opportunities_stage_id_fkey";
            columns: ["stage_id"];
            isOneToOne: false;
            referencedRelation: "pipeline_stages";
            referencedColumns: ["id"];
          },
        ];
      };
      outreach_messages: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string;
          template_id: string | null;
          channel: "email" | "linkedin" | "instagram" | "whatsapp" | "phone" | "other";
          outreach_stage: "first_contact" | "follow_up_1" | "follow_up_2" | "interested_response" | "discovery_call_invitation" | "post_call_follow_up" | "proposal_follow_up" | "re_engagement" | "partner_outreach" | "client_check_in";
          subject: string | null;
          customized_message: string;
          sent_at: string;
          response_status: "sent" | "delivered" | "replied" | "no_response" | "interested" | "not_interested" | "not_now" | "wrong_contact";
          response_date: string | null;
          response_notes: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id: string;
          template_id?: string | null;
          channel: "email" | "linkedin" | "instagram" | "whatsapp" | "phone" | "other";
          outreach_stage: "first_contact" | "follow_up_1" | "follow_up_2" | "interested_response" | "discovery_call_invitation" | "post_call_follow_up" | "proposal_follow_up" | "re_engagement" | "partner_outreach" | "client_check_in";
          subject?: string | null;
          customized_message: string;
          sent_at?: string;
          response_status?: "sent" | "delivered" | "replied" | "no_response" | "interested" | "not_interested" | "not_now" | "wrong_contact";
          response_date?: string | null;
          response_notes?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string;
          template_id?: string | null;
          channel?: "email" | "linkedin" | "instagram" | "whatsapp" | "phone" | "other";
          outreach_stage?: "first_contact" | "follow_up_1" | "follow_up_2" | "interested_response" | "discovery_call_invitation" | "post_call_follow_up" | "proposal_follow_up" | "re_engagement" | "partner_outreach" | "client_check_in";
          subject?: string | null;
          customized_message?: string;
          sent_at?: string;
          response_status?: "sent" | "delivered" | "replied" | "no_response" | "interested" | "not_interested" | "not_now" | "wrong_contact";
          response_date?: string | null;
          response_notes?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "outreach_messages_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "outreach_messages_template_id_fkey";
            columns: ["template_id"];
            isOneToOne: false;
            referencedRelation: "outreach_templates";
            referencedColumns: ["id"];
          },
        ];
      };
      outreach_templates: {
        Row: {
          id: string;
          name: string;
          channel: "email" | "linkedin" | "instagram" | "whatsapp" | "phone" | "other";
          audience: "direct_business" | "startup" | "agency" | "freelancer" | "creator" | "consultant" | "professional" | "other" | "general";
          outreach_stage: "first_contact" | "follow_up_1" | "follow_up_2" | "interested_response" | "discovery_call_invitation" | "post_call_follow_up" | "proposal_follow_up" | "re_engagement" | "partner_outreach" | "client_check_in";
          subject: string | null;
          body: string;
          is_generic: boolean;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          channel: "email" | "linkedin" | "instagram" | "whatsapp" | "phone" | "other";
          audience: "direct_business" | "startup" | "agency" | "freelancer" | "creator" | "consultant" | "professional" | "other" | "general";
          outreach_stage: "first_contact" | "follow_up_1" | "follow_up_2" | "interested_response" | "discovery_call_invitation" | "post_call_follow_up" | "proposal_follow_up" | "re_engagement" | "partner_outreach" | "client_check_in";
          subject?: string | null;
          body: string;
          is_generic?: boolean;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          channel?: "email" | "linkedin" | "instagram" | "whatsapp" | "phone" | "other";
          audience?: "direct_business" | "startup" | "agency" | "freelancer" | "creator" | "consultant" | "professional" | "other" | "general";
          outreach_stage?: "first_contact" | "follow_up_1" | "follow_up_2" | "interested_response" | "discovery_call_invitation" | "post_call_follow_up" | "proposal_follow_up" | "re_engagement" | "partner_outreach" | "client_check_in";
          subject?: string | null;
          body?: string;
          is_generic?: boolean;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      partners: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          contact_name: string | null;
          email: string | null;
          phone: string | null;
          website: string | null;
          linkedin_url: string | null;
          location: string | null;
          partner_type: "development_agency" | "marketing_agency" | "freelancer" | "designer" | "developer" | "consultant" | "software_company" | "seo_agency" | "other";
          services: string[];
          notes: string | null;
          status: "prospect" | "contacted" | "interested" | "active" | "inactive";
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          name: string;
          contact_name?: string | null;
          email?: string | null;
          phone?: string | null;
          website?: string | null;
          linkedin_url?: string | null;
          location?: string | null;
          partner_type?: "development_agency" | "marketing_agency" | "freelancer" | "designer" | "developer" | "consultant" | "software_company" | "seo_agency" | "other";
          services?: string[];
          notes?: string | null;
          status?: "prospect" | "contacted" | "interested" | "active" | "inactive";
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          contact_name?: string | null;
          email?: string | null;
          phone?: string | null;
          website?: string | null;
          linkedin_url?: string | null;
          location?: string | null;
          partner_type?: "development_agency" | "marketing_agency" | "freelancer" | "designer" | "developer" | "consultant" | "software_company" | "seo_agency" | "other";
          services?: string[];
          notes?: string | null;
          status?: "prospect" | "contacted" | "interested" | "active" | "inactive";
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      payments: {
        Row: {
          id: string;
          owner_id: string;
          project_id: string;
          payment_date: string;
          amount: number;
          payment_type: "advance" | "milestone" | "final" | "retainer" | "other";
          status: "expected" | "received" | "failed" | "refunded";
          reference: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          project_id: string;
          payment_date: string;
          amount: number | string;
          payment_type?: "advance" | "milestone" | "final" | "retainer" | "other";
          status?: "expected" | "received" | "failed" | "refunded";
          reference?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          project_id?: string;
          payment_date?: string;
          amount?: number | string;
          payment_type?: "advance" | "milestone" | "final" | "retainer" | "other";
          status?: "expected" | "received" | "failed" | "refunded";
          reference?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
        ];
      };
      pipeline_stages: {
        Row: {
          id: string;
          owner_id: string;
          pipeline_id: string;
          key: "new" | "contacted" | "replied" | "qualified" | "discovery" | "proposal" | "negotiation" | "won" | "lost" | "nurture" | null;
          label: string;
          color: "slate" | "sky" | "blue" | "indigo" | "violet" | "amber" | "orange" | "green" | "red" | "teal";
          kind: "open" | "won" | "lost" | "parked";
          probability: number;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          pipeline_id: string;
          key?: "new" | "contacted" | "replied" | "qualified" | "discovery" | "proposal" | "negotiation" | "won" | "lost" | "nurture" | null;
          label: string;
          color?: "slate" | "sky" | "blue" | "indigo" | "violet" | "amber" | "orange" | "green" | "red" | "teal";
          kind?: "open" | "won" | "lost" | "parked";
          probability?: number;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          pipeline_id?: string;
          key?: "new" | "contacted" | "replied" | "qualified" | "discovery" | "proposal" | "negotiation" | "won" | "lost" | "nurture" | null;
          label?: string;
          color?: "slate" | "sky" | "blue" | "indigo" | "violet" | "amber" | "orange" | "green" | "red" | "teal";
          kind?: "open" | "won" | "lost" | "parked";
          probability?: number;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pipeline_stages_pipeline_id_fkey";
            columns: ["pipeline_id"];
            isOneToOne: false;
            referencedRelation: "pipelines";
            referencedColumns: ["id"];
          },
        ];
      };
      pipelines: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          is_default: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          name: string;
          is_default?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          is_default?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      profiles: {
        Row: {
          id: string;
          email: string | null;
          full_name: string | null;
          role: "admin" | "member" | "pending";
          created_at: string;
          updated_at: string;
          phone: string | null;
          website: string | null;
          linkedin_url: string | null;
          business_name: string | null;
          business_description: string | null;
          business_website: string | null;
          currency: string;
          timezone: string | null;
          follow_up_1_days: number;
          follow_up_2_days: number;
          score_weights: Json | null;
        };
        Insert: {
          id: string;
          email?: string | null;
          full_name?: string | null;
          role?: "admin" | "member" | "pending";
          created_at?: string;
          updated_at?: string;
          phone?: string | null;
          website?: string | null;
          linkedin_url?: string | null;
          business_name?: string | null;
          business_description?: string | null;
          business_website?: string | null;
          currency?: string;
          timezone?: string | null;
          follow_up_1_days?: number;
          follow_up_2_days?: number;
          score_weights?: Json | null;
        };
        Update: {
          id?: string;
          email?: string | null;
          full_name?: string | null;
          role?: "admin" | "member" | "pending";
          created_at?: string;
          updated_at?: string;
          phone?: string | null;
          website?: string | null;
          linkedin_url?: string | null;
          business_name?: string | null;
          business_description?: string | null;
          business_website?: string | null;
          currency?: string;
          timezone?: string | null;
          follow_up_1_days?: number;
          follow_up_2_days?: number;
          score_weights?: Json | null;
        };
        Relationships: [
        ];
      };
      projects: {
        Row: {
          id: string;
          owner_id: string;
          client_id: string;
          opportunity_id: string | null;
          service_id: string | null;
          partner_id: string | null;
          name: string;
          delivery_model: "self_delivered" | "partner_delivered" | "referral" | "white_label" | "joint_delivery" | null;
          total_project_value: number | null;
          start_date: string | null;
          expected_end_date: string | null;
          status: "not_started" | "active" | "on_hold" | "completed" | "cancelled";
          notes: string | null;
          revenue_model: "direct_revenue" | "referral_commission" | "partner_commission" | "revenue_share" | "fixed_fee" | "other" | null;
          payment_flow: "client_pays_me" | "client_pays_partner";
          partner_cost: number | null;
          commission_type: "none" | "percentage" | "fixed" | null;
          commission_percentage: number | null;
          fixed_commission: number | null;
          commission_basis: "total_project_value" | "amount_received" | "net_revenue" | "custom" | null;
          commission_custom_base: number | null;
          commission_received: number;
          commission_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          client_id: string;
          opportunity_id?: string | null;
          service_id?: string | null;
          partner_id?: string | null;
          name: string;
          delivery_model?: "self_delivered" | "partner_delivered" | "referral" | "white_label" | "joint_delivery" | null;
          total_project_value?: number | string | null;
          start_date?: string | null;
          expected_end_date?: string | null;
          status?: "not_started" | "active" | "on_hold" | "completed" | "cancelled";
          notes?: string | null;
          revenue_model?: "direct_revenue" | "referral_commission" | "partner_commission" | "revenue_share" | "fixed_fee" | "other" | null;
          payment_flow?: "client_pays_me" | "client_pays_partner";
          partner_cost?: number | string | null;
          commission_type?: "none" | "percentage" | "fixed" | null;
          commission_percentage?: number | string | null;
          fixed_commission?: number | string | null;
          commission_basis?: "total_project_value" | "amount_received" | "net_revenue" | "custom" | null;
          commission_custom_base?: number | string | null;
          commission_received?: number | string;
          commission_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          client_id?: string;
          opportunity_id?: string | null;
          service_id?: string | null;
          partner_id?: string | null;
          name?: string;
          delivery_model?: "self_delivered" | "partner_delivered" | "referral" | "white_label" | "joint_delivery" | null;
          total_project_value?: number | string | null;
          start_date?: string | null;
          expected_end_date?: string | null;
          status?: "not_started" | "active" | "on_hold" | "completed" | "cancelled";
          notes?: string | null;
          revenue_model?: "direct_revenue" | "referral_commission" | "partner_commission" | "revenue_share" | "fixed_fee" | "other" | null;
          payment_flow?: "client_pays_me" | "client_pays_partner";
          partner_cost?: number | string | null;
          commission_type?: "none" | "percentage" | "fixed" | null;
          commission_percentage?: number | string | null;
          fixed_commission?: number | string | null;
          commission_basis?: "total_project_value" | "amount_received" | "net_revenue" | "custom" | null;
          commission_custom_base?: number | string | null;
          commission_received?: number | string;
          commission_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "projects_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "clients";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "projects_opportunity_id_fkey";
            columns: ["opportunity_id"];
            isOneToOne: false;
            referencedRelation: "opportunities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "projects_partner_id_fkey";
            columns: ["partner_id"];
            isOneToOne: false;
            referencedRelation: "partners";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "projects_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      prospect_contacts: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string;
          name: string;
          job_title: string | null;
          email: string | null;
          phone: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id: string;
          name: string;
          job_title?: string | null;
          email?: string | null;
          phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string;
          name?: string;
          job_title?: string | null;
          email?: string | null;
          phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "prospect_contacts_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
        ];
      };
      prospects: {
        Row: {
          id: string;
          owner_id: string;
          business_name: string;
          contact_name: string | null;
          job_title: string | null;
          email: string | null;
          phone: string | null;
          whatsapp: string | null;
          website: string | null;
          linkedin_url: string | null;
          instagram_url: string | null;
          location: string | null;
          country: string | null;
          industry: string | null;
          company_size: "1" | "2-10" | "11-50" | "51-200" | "201-500" | "500+" | null;
          lead_source: string;
          source_url: string | null;
          source_notes: string | null;
          prospect_type: "direct_business" | "startup" | "agency" | "freelancer" | "creator" | "consultant" | "professional" | "other";
          stage: "new" | "contacted" | "replied" | "qualified" | "nurture" | "client" | "lost";
          stage_changed_at: string;
          furthest_stage: "new" | "contacted" | "replied" | "qualified" | "client";
          lost_reason: string | null;
          business_description: string | null;
          current_website_notes: string | null;
          website_quality: "none" | "poor" | "average" | "good" | "excellent" | null;
          social_presence: string | null;
          observed_problem: string | null;
          potential_need: string | null;
          suggested_solution: string | null;
          research_notes: string | null;
          has_website: boolean | null;
          website_needs_improvement: boolean | null;
          has_online_booking: boolean | null;
          has_lead_form: boolean | null;
          has_whatsapp: boolean | null;
          has_customer_portal: boolean | null;
          has_admin_panel: boolean | null;
          has_ecommerce: boolean | null;
          has_lms: boolean | null;
          has_automation: boolean | null;
          has_ai_features: boolean | null;
          potential_project: string | null;
          potential_project_notes: string | null;
          estimated_value: number | null;
          recommended_services: string[];
          score_factors: Json;
          opportunity_score: number;
          lead_temperature: "cold" | "warm" | "hot";
          website_domain: string | null;
          email_normalized: string | null;
          phone_normalized: string | null;
          whatsapp_normalized: string | null;
          name_location_key: string | null;
          last_contacted_at: string | null;
          last_activity_at: string | null;
          next_follow_up_date: string | null;
          is_demo: boolean;
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          business_name: string;
          contact_name?: string | null;
          job_title?: string | null;
          email?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          website?: string | null;
          linkedin_url?: string | null;
          instagram_url?: string | null;
          location?: string | null;
          country?: string | null;
          industry?: string | null;
          company_size?: "1" | "2-10" | "11-50" | "51-200" | "201-500" | "500+" | null;
          lead_source?: string;
          source_url?: string | null;
          source_notes?: string | null;
          prospect_type?: "direct_business" | "startup" | "agency" | "freelancer" | "creator" | "consultant" | "professional" | "other";
          stage?: "new" | "contacted" | "replied" | "qualified" | "nurture" | "client" | "lost";
          stage_changed_at?: string;
          furthest_stage?: "new" | "contacted" | "replied" | "qualified" | "client";
          lost_reason?: string | null;
          business_description?: string | null;
          current_website_notes?: string | null;
          website_quality?: "none" | "poor" | "average" | "good" | "excellent" | null;
          social_presence?: string | null;
          observed_problem?: string | null;
          potential_need?: string | null;
          suggested_solution?: string | null;
          research_notes?: string | null;
          has_website?: boolean | null;
          website_needs_improvement?: boolean | null;
          has_online_booking?: boolean | null;
          has_lead_form?: boolean | null;
          has_whatsapp?: boolean | null;
          has_customer_portal?: boolean | null;
          has_admin_panel?: boolean | null;
          has_ecommerce?: boolean | null;
          has_lms?: boolean | null;
          has_automation?: boolean | null;
          has_ai_features?: boolean | null;
          potential_project?: string | null;
          potential_project_notes?: string | null;
          estimated_value?: number | string | null;
          recommended_services?: string[];
          score_factors?: Json;
          opportunity_score?: number;
          lead_temperature?: "cold" | "warm" | "hot";
          website_domain?: string | null;
          email_normalized?: string | null;
          phone_normalized?: string | null;
          whatsapp_normalized?: string | null;
          name_location_key?: string | null;
          last_contacted_at?: string | null;
          last_activity_at?: string | null;
          next_follow_up_date?: string | null;
          is_demo?: boolean;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          business_name?: string;
          contact_name?: string | null;
          job_title?: string | null;
          email?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          website?: string | null;
          linkedin_url?: string | null;
          instagram_url?: string | null;
          location?: string | null;
          country?: string | null;
          industry?: string | null;
          company_size?: "1" | "2-10" | "11-50" | "51-200" | "201-500" | "500+" | null;
          lead_source?: string;
          source_url?: string | null;
          source_notes?: string | null;
          prospect_type?: "direct_business" | "startup" | "agency" | "freelancer" | "creator" | "consultant" | "professional" | "other";
          stage?: "new" | "contacted" | "replied" | "qualified" | "nurture" | "client" | "lost";
          stage_changed_at?: string;
          furthest_stage?: "new" | "contacted" | "replied" | "qualified" | "client";
          lost_reason?: string | null;
          business_description?: string | null;
          current_website_notes?: string | null;
          website_quality?: "none" | "poor" | "average" | "good" | "excellent" | null;
          social_presence?: string | null;
          observed_problem?: string | null;
          potential_need?: string | null;
          suggested_solution?: string | null;
          research_notes?: string | null;
          has_website?: boolean | null;
          website_needs_improvement?: boolean | null;
          has_online_booking?: boolean | null;
          has_lead_form?: boolean | null;
          has_whatsapp?: boolean | null;
          has_customer_portal?: boolean | null;
          has_admin_panel?: boolean | null;
          has_ecommerce?: boolean | null;
          has_lms?: boolean | null;
          has_automation?: boolean | null;
          has_ai_features?: boolean | null;
          potential_project?: string | null;
          potential_project_notes?: string | null;
          estimated_value?: number | string | null;
          recommended_services?: string[];
          score_factors?: Json;
          opportunity_score?: number;
          lead_temperature?: "cold" | "warm" | "hot";
          website_domain?: string | null;
          email_normalized?: string | null;
          phone_normalized?: string | null;
          whatsapp_normalized?: string | null;
          name_location_key?: string | null;
          last_contacted_at?: string | null;
          last_activity_at?: string | null;
          next_follow_up_date?: string | null;
          is_demo?: boolean;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      qualification_assessments: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string;
          business_model: string | null;
          current_technology: string | null;
          problem_description: string | null;
          current_solution: string | null;
          whats_not_working: string | null;
          cost_of_inaction: string | null;
          project_type: "website" | "ecommerce" | "web_application" | "saas" | "crm" | "erp" | "lms" | "dashboard" | "ai_genai" | "api_backend" | "automation" | "mobile_application" | "custom_software" | "other" | null;
          required_features: string | null;
          integrations: string | null;
          number_of_users: string | null;
          estimated_complexity: "low" | "medium" | "high" | "unknown" | null;
          desired_launch_date: string | null;
          timeline_notes: string | null;
          budget_min: number | null;
          budget_max: number | null;
          budget_notes: string | null;
          decision_maker_identified: boolean;
          decision_maker_name: string | null;
          decision_process: string | null;
          other_stakeholders: string | null;
          need_clarity: number;
          budget_fit: number;
          timeline_fit: number;
          decision_maker_access: number;
          urgency: number;
          score: number;
          suggested_classification: "unqualified" | "potential" | "qualified" | "high_priority";
          classification: "unqualified" | "potential" | "qualified" | "high_priority";
          notes: string | null;
          created_at: string;
          updated_at: string;
          opportunity_id: string | null;
          solution_fit: number | null;
          delivery_feasibility: number | null;
          custom_answers: Json;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id: string;
          business_model?: string | null;
          current_technology?: string | null;
          problem_description?: string | null;
          current_solution?: string | null;
          whats_not_working?: string | null;
          cost_of_inaction?: string | null;
          project_type?: "website" | "ecommerce" | "web_application" | "saas" | "crm" | "erp" | "lms" | "dashboard" | "ai_genai" | "api_backend" | "automation" | "mobile_application" | "custom_software" | "other" | null;
          required_features?: string | null;
          integrations?: string | null;
          number_of_users?: string | null;
          estimated_complexity?: "low" | "medium" | "high" | "unknown" | null;
          desired_launch_date?: string | null;
          timeline_notes?: string | null;
          budget_min?: number | string | null;
          budget_max?: number | string | null;
          budget_notes?: string | null;
          decision_maker_identified?: boolean;
          decision_maker_name?: string | null;
          decision_process?: string | null;
          other_stakeholders?: string | null;
          need_clarity: number;
          budget_fit: number;
          timeline_fit: number;
          decision_maker_access: number;
          urgency: number;
          score: number;
          suggested_classification: "unqualified" | "potential" | "qualified" | "high_priority";
          classification: "unqualified" | "potential" | "qualified" | "high_priority";
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          opportunity_id?: string | null;
          solution_fit?: number | null;
          delivery_feasibility?: number | null;
          custom_answers?: Json;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string;
          business_model?: string | null;
          current_technology?: string | null;
          problem_description?: string | null;
          current_solution?: string | null;
          whats_not_working?: string | null;
          cost_of_inaction?: string | null;
          project_type?: "website" | "ecommerce" | "web_application" | "saas" | "crm" | "erp" | "lms" | "dashboard" | "ai_genai" | "api_backend" | "automation" | "mobile_application" | "custom_software" | "other" | null;
          required_features?: string | null;
          integrations?: string | null;
          number_of_users?: string | null;
          estimated_complexity?: "low" | "medium" | "high" | "unknown" | null;
          desired_launch_date?: string | null;
          timeline_notes?: string | null;
          budget_min?: number | string | null;
          budget_max?: number | string | null;
          budget_notes?: string | null;
          decision_maker_identified?: boolean;
          decision_maker_name?: string | null;
          decision_process?: string | null;
          other_stakeholders?: string | null;
          need_clarity?: number;
          budget_fit?: number;
          timeline_fit?: number;
          decision_maker_access?: number;
          urgency?: number;
          score?: number;
          suggested_classification?: "unqualified" | "potential" | "qualified" | "high_priority";
          classification?: "unqualified" | "potential" | "qualified" | "high_priority";
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          opportunity_id?: string | null;
          solution_fit?: number | null;
          delivery_feasibility?: number | null;
          custom_answers?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "qualification_assessments_opportunity_id_fkey";
            columns: ["opportunity_id"];
            isOneToOne: false;
            referencedRelation: "opportunities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "qualification_assessments_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
        ];
      };
      qualification_questions: {
        Row: {
          id: string;
          owner_id: string;
          question: string;
          help_text: string | null;
          sort_order: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          question: string;
          help_text?: string | null;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          question?: string;
          help_text?: string | null;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      services: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          category: string | null;
          description: string | null;
          target_customer: string | null;
          typical_problem: string | null;
          delivery_model: "self_delivered" | "partner_delivered" | "referral" | "white_label" | "joint_delivery" | null;
          pricing_model: "fixed_price" | "hourly" | "retainer" | "per_project" | "commission" | "custom" | null;
          default_price: number | null;
          discovery_questions: string[];
          notes: string | null;
          active: boolean;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          name: string;
          category?: string | null;
          description?: string | null;
          target_customer?: string | null;
          typical_problem?: string | null;
          delivery_model?: "self_delivered" | "partner_delivered" | "referral" | "white_label" | "joint_delivery" | null;
          pricing_model?: "fixed_price" | "hourly" | "retainer" | "per_project" | "commission" | "custom" | null;
          default_price?: number | string | null;
          discovery_questions?: string[];
          notes?: string | null;
          active?: boolean;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          category?: string | null;
          description?: string | null;
          target_customer?: string | null;
          typical_problem?: string | null;
          delivery_model?: "self_delivered" | "partner_delivered" | "referral" | "white_label" | "joint_delivery" | null;
          pricing_model?: "fixed_price" | "hourly" | "retainer" | "per_project" | "commission" | "custom" | null;
          default_price?: number | string | null;
          discovery_questions?: string[];
          notes?: string | null;
          active?: boolean;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      tasks: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string | null;
          task_type: "first_outreach" | "follow_up" | "discovery_call" | "proposal_follow_up" | "qualification" | "client_follow_up" | "partner_follow_up" | "internal_follow_up" | "handoff" | "other";
          title: string;
          due_date: string;
          due_time: string | null;
          priority: "low" | "medium" | "high" | "urgent";
          status: "pending" | "completed" | "snoozed" | "cancelled";
          notes: string | null;
          is_automated: boolean;
          sequence_step: "follow_up_1" | "follow_up_2" | null;
          outreach_message_id: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
          opportunity_id: string | null;
          client_id: string | null;
          partner_id: string | null;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id?: string | null;
          task_type: "first_outreach" | "follow_up" | "discovery_call" | "proposal_follow_up" | "qualification" | "client_follow_up" | "partner_follow_up" | "internal_follow_up" | "handoff" | "other";
          title: string;
          due_date: string;
          due_time?: string | null;
          priority?: "low" | "medium" | "high" | "urgent";
          status?: "pending" | "completed" | "snoozed" | "cancelled";
          notes?: string | null;
          is_automated?: boolean;
          sequence_step?: "follow_up_1" | "follow_up_2" | null;
          outreach_message_id?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          opportunity_id?: string | null;
          client_id?: string | null;
          partner_id?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string | null;
          task_type?: "first_outreach" | "follow_up" | "discovery_call" | "proposal_follow_up" | "qualification" | "client_follow_up" | "partner_follow_up" | "internal_follow_up" | "handoff" | "other";
          title?: string;
          due_date?: string;
          due_time?: string | null;
          priority?: "low" | "medium" | "high" | "urgent";
          status?: "pending" | "completed" | "snoozed" | "cancelled";
          notes?: string | null;
          is_automated?: boolean;
          sequence_step?: "follow_up_1" | "follow_up_2" | null;
          outreach_message_id?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          opportunity_id?: string | null;
          client_id?: string | null;
          partner_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "clients";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_opportunity_id_fkey";
            columns: ["opportunity_id"];
            isOneToOne: false;
            referencedRelation: "opportunities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_outreach_message_id_fkey";
            columns: ["outreach_message_id"];
            isOneToOne: false;
            referencedRelation: "outreach_messages";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_partner_id_fkey";
            columns: ["partner_id"];
            isOneToOne: false;
            referencedRelation: "partners";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_member: { Args: Record<PropertyKey, never>; Returns: boolean };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicTables = Database["public"]["Tables"];
export type Tables<T extends keyof PublicTables> = PublicTables[T]["Row"];
export type TablesInsert<T extends keyof PublicTables> = PublicTables[T]["Insert"];
export type TablesUpdate<T extends keyof PublicTables> = PublicTables[T]["Update"];
