// Generated by scripts/gen-db-types.mjs — do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      activities: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string;
          activity_type: "prospect_created" | "prospect_updated" | "note" | "stage_change" | "outreach_sent" | "response_recorded" | "task_created" | "task_completed" | "task_rescheduled" | "task_cancelled" | "qualification" | "handoff" | "opportunity" | "archived" | "restored";
          title: string;
          details: string | null;
          metadata: Json;
          occurred_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id: string;
          activity_type: "prospect_created" | "prospect_updated" | "note" | "stage_change" | "outreach_sent" | "response_recorded" | "task_created" | "task_completed" | "task_rescheduled" | "task_cancelled" | "qualification" | "handoff" | "opportunity" | "archived" | "restored";
          title: string;
          details?: string | null;
          metadata?: Json;
          occurred_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string;
          activity_type?: "prospect_created" | "prospect_updated" | "note" | "stage_change" | "outreach_sent" | "response_recorded" | "task_created" | "task_completed" | "task_rescheduled" | "task_cancelled" | "qualification" | "handoff" | "opportunity" | "archived" | "restored";
          title?: string;
          details?: string | null;
          metadata?: Json;
          occurred_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "activities_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
        ];
      };
      commission_settings: {
        Row: {
          id: string;
          tier_name: string;
          min_amount: number;
          max_amount: number | null;
          percentage: number;
          sort_order: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tier_name: string;
          min_amount: number | string;
          max_amount?: number | string | null;
          percentage: number | string;
          sort_order?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tier_name?: string;
          min_amount?: number | string;
          max_amount?: number | string | null;
          percentage?: number | string;
          sort_order?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      handoffs: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string;
          qualification_id: string | null;
          status: "draft" | "sent" | "accepted" | "declined";
          summary_markdown: string;
          snapshot: Json;
          sent_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id: string;
          qualification_id?: string | null;
          status?: "draft" | "sent" | "accepted" | "declined";
          summary_markdown: string;
          snapshot?: Json;
          sent_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string;
          qualification_id?: string | null;
          status?: "draft" | "sent" | "accepted" | "declined";
          summary_markdown?: string;
          snapshot?: Json;
          sent_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "handoffs_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "handoffs_qualification_id_fkey";
            columns: ["qualification_id"];
            isOneToOne: false;
            referencedRelation: "qualification_assessments";
            referencedColumns: ["id"];
          },
        ];
      };
      opportunities: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string;
          title: string;
          project_type: string | null;
          status: "open" | "won" | "lost";
          estimated_value: number | null;
          eligible_project_amount: number | null;
          agreed_commission_pct: number | null;
          eligible_amount_received: number;
          commission_paid: number;
          pass_through_notes: string | null;
          expected_close_date: string | null;
          closed_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id: string;
          title: string;
          project_type?: string | null;
          status?: "open" | "won" | "lost";
          estimated_value?: number | string | null;
          eligible_project_amount?: number | string | null;
          agreed_commission_pct?: number | string | null;
          eligible_amount_received?: number | string;
          commission_paid?: number | string;
          pass_through_notes?: string | null;
          expected_close_date?: string | null;
          closed_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string;
          title?: string;
          project_type?: string | null;
          status?: "open" | "won" | "lost";
          estimated_value?: number | string | null;
          eligible_project_amount?: number | string | null;
          agreed_commission_pct?: number | string | null;
          eligible_amount_received?: number | string;
          commission_paid?: number | string;
          pass_through_notes?: string | null;
          expected_close_date?: string | null;
          closed_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "opportunities_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
        ];
      };
      outreach_messages: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string;
          template_id: string | null;
          channel: "email" | "linkedin" | "instagram" | "whatsapp" | "phone" | "other";
          outreach_stage: "first_contact" | "follow_up_1" | "follow_up_2" | "interested_response" | "discovery_call_invitation" | "post_call_follow_up" | "proposal_follow_up" | "re_engagement";
          subject: string | null;
          customized_message: string;
          sent_at: string;
          response_status: "sent" | "delivered" | "replied" | "no_response" | "interested" | "not_interested" | "not_now" | "wrong_contact";
          response_date: string | null;
          response_notes: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id: string;
          template_id?: string | null;
          channel: "email" | "linkedin" | "instagram" | "whatsapp" | "phone" | "other";
          outreach_stage: "first_contact" | "follow_up_1" | "follow_up_2" | "interested_response" | "discovery_call_invitation" | "post_call_follow_up" | "proposal_follow_up" | "re_engagement";
          subject?: string | null;
          customized_message: string;
          sent_at?: string;
          response_status?: "sent" | "delivered" | "replied" | "no_response" | "interested" | "not_interested" | "not_now" | "wrong_contact";
          response_date?: string | null;
          response_notes?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string;
          template_id?: string | null;
          channel?: "email" | "linkedin" | "instagram" | "whatsapp" | "phone" | "other";
          outreach_stage?: "first_contact" | "follow_up_1" | "follow_up_2" | "interested_response" | "discovery_call_invitation" | "post_call_follow_up" | "proposal_follow_up" | "re_engagement";
          subject?: string | null;
          customized_message?: string;
          sent_at?: string;
          response_status?: "sent" | "delivered" | "replied" | "no_response" | "interested" | "not_interested" | "not_now" | "wrong_contact";
          response_date?: string | null;
          response_notes?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "outreach_messages_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "outreach_messages_template_id_fkey";
            columns: ["template_id"];
            isOneToOne: false;
            referencedRelation: "outreach_templates";
            referencedColumns: ["id"];
          },
        ];
      };
      outreach_templates: {
        Row: {
          id: string;
          name: string;
          channel: "email" | "linkedin" | "instagram" | "whatsapp";
          audience: "direct_business" | "marketing_agency" | "seo_agency" | "branding_agency" | "social_media_agency" | "startup" | "education" | "healthcare" | "ecommerce" | "professional_services" | "general";
          outreach_stage: "first_contact" | "follow_up_1" | "follow_up_2" | "interested_response" | "discovery_call_invitation" | "post_call_follow_up" | "proposal_follow_up" | "re_engagement";
          subject: string | null;
          body: string;
          is_generic: boolean;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          channel: "email" | "linkedin" | "instagram" | "whatsapp";
          audience: "direct_business" | "marketing_agency" | "seo_agency" | "branding_agency" | "social_media_agency" | "startup" | "education" | "healthcare" | "ecommerce" | "professional_services" | "general";
          outreach_stage: "first_contact" | "follow_up_1" | "follow_up_2" | "interested_response" | "discovery_call_invitation" | "post_call_follow_up" | "proposal_follow_up" | "re_engagement";
          subject?: string | null;
          body: string;
          is_generic?: boolean;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          channel?: "email" | "linkedin" | "instagram" | "whatsapp";
          audience?: "direct_business" | "marketing_agency" | "seo_agency" | "branding_agency" | "social_media_agency" | "startup" | "education" | "healthcare" | "ecommerce" | "professional_services" | "general";
          outreach_stage?: "first_contact" | "follow_up_1" | "follow_up_2" | "interested_response" | "discovery_call_invitation" | "post_call_follow_up" | "proposal_follow_up" | "re_engagement";
          subject?: string | null;
          body?: string;
          is_generic?: boolean;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      profiles: {
        Row: {
          id: string;
          email: string | null;
          full_name: string | null;
          role: "admin" | "member" | "pending";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          full_name?: string | null;
          role?: "admin" | "member" | "pending";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          full_name?: string | null;
          role?: "admin" | "member" | "pending";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      project_types: {
        Row: {
          id: string;
          slug: string;
          service_id: string | null;
          name: string;
          description: string | null;
          typical_client: string | null;
          typical_problem: string | null;
          potential_solution: string | null;
          discovery_questions: string[];
          notes: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          service_id?: string | null;
          name: string;
          description?: string | null;
          typical_client?: string | null;
          typical_problem?: string | null;
          potential_solution?: string | null;
          discovery_questions?: string[];
          notes?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          service_id?: string | null;
          name?: string;
          description?: string | null;
          typical_client?: string | null;
          typical_problem?: string | null;
          potential_solution?: string | null;
          discovery_questions?: string[];
          notes?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "project_types_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      prospect_contacts: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string;
          name: string;
          job_title: string | null;
          email: string | null;
          phone: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id: string;
          name: string;
          job_title?: string | null;
          email?: string | null;
          phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string;
          name?: string;
          job_title?: string | null;
          email?: string | null;
          phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "prospect_contacts_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
        ];
      };
      prospects: {
        Row: {
          id: string;
          owner_id: string;
          business_name: string;
          contact_name: string | null;
          job_title: string | null;
          email: string | null;
          phone: string | null;
          whatsapp: string | null;
          website: string | null;
          linkedin_url: string | null;
          instagram_url: string | null;
          location: string | null;
          country: string | null;
          industry: string | null;
          company_size: "1" | "2-10" | "11-50" | "51-200" | "201-500" | "500+" | null;
          lead_source: "google_maps" | "linkedin" | "instagram" | "cold_email" | "whatsapp" | "referral" | "upwork" | "contra" | "freelancer" | "networking" | "agency_prospecting" | "other";
          source_url: string | null;
          source_notes: string | null;
          prospect_type: "direct_business" | "startup" | "marketing_agency" | "seo_agency" | "branding_agency" | "social_media_agency" | "web_design_agency" | "other";
          stage: "prospect" | "contacted" | "replied" | "qualified" | "discovery_call" | "technical_discussion" | "proposal_sent" | "negotiation" | "won" | "lost";
          stage_changed_at: string;
          furthest_stage: "prospect" | "contacted" | "replied" | "qualified" | "discovery_call" | "technical_discussion" | "proposal_sent" | "negotiation" | "won";
          lost_reason: string | null;
          business_description: string | null;
          current_website_notes: string | null;
          website_quality: "none" | "poor" | "average" | "good" | "excellent" | null;
          social_presence: string | null;
          observed_problem: string | null;
          potential_need: string | null;
          suggested_solution: string | null;
          research_notes: string | null;
          has_website: boolean | null;
          website_needs_improvement: boolean | null;
          has_online_booking: boolean | null;
          has_lead_form: boolean | null;
          has_whatsapp: boolean | null;
          has_customer_portal: boolean | null;
          has_admin_panel: boolean | null;
          has_ecommerce: boolean | null;
          has_lms: boolean | null;
          has_automation: boolean | null;
          has_ai_features: boolean | null;
          potential_project: string | null;
          potential_project_notes: string | null;
          estimated_value: number | null;
          recommended_services: string[];
          score_factors: Json;
          opportunity_score: number;
          lead_temperature: "cold" | "warm" | "hot";
          website_domain: string | null;
          email_normalized: string | null;
          phone_normalized: string | null;
          whatsapp_normalized: string | null;
          name_location_key: string | null;
          last_contacted_at: string | null;
          last_activity_at: string | null;
          next_follow_up_date: string | null;
          is_demo: boolean;
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          business_name: string;
          contact_name?: string | null;
          job_title?: string | null;
          email?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          website?: string | null;
          linkedin_url?: string | null;
          instagram_url?: string | null;
          location?: string | null;
          country?: string | null;
          industry?: string | null;
          company_size?: "1" | "2-10" | "11-50" | "51-200" | "201-500" | "500+" | null;
          lead_source?: "google_maps" | "linkedin" | "instagram" | "cold_email" | "whatsapp" | "referral" | "upwork" | "contra" | "freelancer" | "networking" | "agency_prospecting" | "other";
          source_url?: string | null;
          source_notes?: string | null;
          prospect_type?: "direct_business" | "startup" | "marketing_agency" | "seo_agency" | "branding_agency" | "social_media_agency" | "web_design_agency" | "other";
          stage?: "prospect" | "contacted" | "replied" | "qualified" | "discovery_call" | "technical_discussion" | "proposal_sent" | "negotiation" | "won" | "lost";
          stage_changed_at?: string;
          furthest_stage?: "prospect" | "contacted" | "replied" | "qualified" | "discovery_call" | "technical_discussion" | "proposal_sent" | "negotiation" | "won";
          lost_reason?: string | null;
          business_description?: string | null;
          current_website_notes?: string | null;
          website_quality?: "none" | "poor" | "average" | "good" | "excellent" | null;
          social_presence?: string | null;
          observed_problem?: string | null;
          potential_need?: string | null;
          suggested_solution?: string | null;
          research_notes?: string | null;
          has_website?: boolean | null;
          website_needs_improvement?: boolean | null;
          has_online_booking?: boolean | null;
          has_lead_form?: boolean | null;
          has_whatsapp?: boolean | null;
          has_customer_portal?: boolean | null;
          has_admin_panel?: boolean | null;
          has_ecommerce?: boolean | null;
          has_lms?: boolean | null;
          has_automation?: boolean | null;
          has_ai_features?: boolean | null;
          potential_project?: string | null;
          potential_project_notes?: string | null;
          estimated_value?: number | string | null;
          recommended_services?: string[];
          score_factors?: Json;
          opportunity_score?: number;
          lead_temperature?: "cold" | "warm" | "hot";
          website_domain?: string | null;
          email_normalized?: string | null;
          phone_normalized?: string | null;
          whatsapp_normalized?: string | null;
          name_location_key?: string | null;
          last_contacted_at?: string | null;
          last_activity_at?: string | null;
          next_follow_up_date?: string | null;
          is_demo?: boolean;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          business_name?: string;
          contact_name?: string | null;
          job_title?: string | null;
          email?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          website?: string | null;
          linkedin_url?: string | null;
          instagram_url?: string | null;
          location?: string | null;
          country?: string | null;
          industry?: string | null;
          company_size?: "1" | "2-10" | "11-50" | "51-200" | "201-500" | "500+" | null;
          lead_source?: "google_maps" | "linkedin" | "instagram" | "cold_email" | "whatsapp" | "referral" | "upwork" | "contra" | "freelancer" | "networking" | "agency_prospecting" | "other";
          source_url?: string | null;
          source_notes?: string | null;
          prospect_type?: "direct_business" | "startup" | "marketing_agency" | "seo_agency" | "branding_agency" | "social_media_agency" | "web_design_agency" | "other";
          stage?: "prospect" | "contacted" | "replied" | "qualified" | "discovery_call" | "technical_discussion" | "proposal_sent" | "negotiation" | "won" | "lost";
          stage_changed_at?: string;
          furthest_stage?: "prospect" | "contacted" | "replied" | "qualified" | "discovery_call" | "technical_discussion" | "proposal_sent" | "negotiation" | "won";
          lost_reason?: string | null;
          business_description?: string | null;
          current_website_notes?: string | null;
          website_quality?: "none" | "poor" | "average" | "good" | "excellent" | null;
          social_presence?: string | null;
          observed_problem?: string | null;
          potential_need?: string | null;
          suggested_solution?: string | null;
          research_notes?: string | null;
          has_website?: boolean | null;
          website_needs_improvement?: boolean | null;
          has_online_booking?: boolean | null;
          has_lead_form?: boolean | null;
          has_whatsapp?: boolean | null;
          has_customer_portal?: boolean | null;
          has_admin_panel?: boolean | null;
          has_ecommerce?: boolean | null;
          has_lms?: boolean | null;
          has_automation?: boolean | null;
          has_ai_features?: boolean | null;
          potential_project?: string | null;
          potential_project_notes?: string | null;
          estimated_value?: number | string | null;
          recommended_services?: string[];
          score_factors?: Json;
          opportunity_score?: number;
          lead_temperature?: "cold" | "warm" | "hot";
          website_domain?: string | null;
          email_normalized?: string | null;
          phone_normalized?: string | null;
          whatsapp_normalized?: string | null;
          name_location_key?: string | null;
          last_contacted_at?: string | null;
          last_activity_at?: string | null;
          next_follow_up_date?: string | null;
          is_demo?: boolean;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      qualification_assessments: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string;
          business_model: string | null;
          current_technology: string | null;
          problem_description: string | null;
          current_solution: string | null;
          whats_not_working: string | null;
          cost_of_inaction: string | null;
          project_type: "website" | "ecommerce" | "web_application" | "saas" | "crm" | "erp" | "lms" | "dashboard" | "ai_genai" | "api_backend" | "automation" | "mobile_application" | "custom_software" | "other" | null;
          required_features: string | null;
          integrations: string | null;
          number_of_users: string | null;
          estimated_complexity: "low" | "medium" | "high" | "unknown" | null;
          desired_launch_date: string | null;
          timeline_notes: string | null;
          budget_min: number | null;
          budget_max: number | null;
          budget_notes: string | null;
          decision_maker_identified: boolean;
          decision_maker_name: string | null;
          decision_process: string | null;
          other_stakeholders: string | null;
          need_clarity: number;
          budget_fit: number;
          timeline_fit: number;
          decision_maker_access: number;
          urgency: number;
          score: number;
          suggested_classification: "unqualified" | "potential" | "qualified" | "high_priority";
          classification: "unqualified" | "potential" | "qualified" | "high_priority";
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id: string;
          business_model?: string | null;
          current_technology?: string | null;
          problem_description?: string | null;
          current_solution?: string | null;
          whats_not_working?: string | null;
          cost_of_inaction?: string | null;
          project_type?: "website" | "ecommerce" | "web_application" | "saas" | "crm" | "erp" | "lms" | "dashboard" | "ai_genai" | "api_backend" | "automation" | "mobile_application" | "custom_software" | "other" | null;
          required_features?: string | null;
          integrations?: string | null;
          number_of_users?: string | null;
          estimated_complexity?: "low" | "medium" | "high" | "unknown" | null;
          desired_launch_date?: string | null;
          timeline_notes?: string | null;
          budget_min?: number | string | null;
          budget_max?: number | string | null;
          budget_notes?: string | null;
          decision_maker_identified?: boolean;
          decision_maker_name?: string | null;
          decision_process?: string | null;
          other_stakeholders?: string | null;
          need_clarity: number;
          budget_fit: number;
          timeline_fit: number;
          decision_maker_access: number;
          urgency: number;
          score: number;
          suggested_classification: "unqualified" | "potential" | "qualified" | "high_priority";
          classification: "unqualified" | "potential" | "qualified" | "high_priority";
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string;
          business_model?: string | null;
          current_technology?: string | null;
          problem_description?: string | null;
          current_solution?: string | null;
          whats_not_working?: string | null;
          cost_of_inaction?: string | null;
          project_type?: "website" | "ecommerce" | "web_application" | "saas" | "crm" | "erp" | "lms" | "dashboard" | "ai_genai" | "api_backend" | "automation" | "mobile_application" | "custom_software" | "other" | null;
          required_features?: string | null;
          integrations?: string | null;
          number_of_users?: string | null;
          estimated_complexity?: "low" | "medium" | "high" | "unknown" | null;
          desired_launch_date?: string | null;
          timeline_notes?: string | null;
          budget_min?: number | string | null;
          budget_max?: number | string | null;
          budget_notes?: string | null;
          decision_maker_identified?: boolean;
          decision_maker_name?: string | null;
          decision_process?: string | null;
          other_stakeholders?: string | null;
          need_clarity?: number;
          budget_fit?: number;
          timeline_fit?: number;
          decision_maker_access?: number;
          urgency?: number;
          score?: number;
          suggested_classification?: "unqualified" | "potential" | "qualified" | "high_priority";
          classification?: "unqualified" | "potential" | "qualified" | "high_priority";
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "qualification_assessments_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
        ];
      };
      services: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          examples: string[];
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string | null;
          examples?: string[];
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          examples?: string[];
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      tasks: {
        Row: {
          id: string;
          owner_id: string;
          prospect_id: string | null;
          task_type: "first_outreach" | "follow_up" | "discovery_call" | "proposal_follow_up" | "qualification" | "internal_follow_up" | "handoff" | "other";
          title: string;
          due_date: string;
          due_time: string | null;
          priority: "low" | "medium" | "high" | "urgent";
          status: "pending" | "completed" | "snoozed" | "cancelled";
          notes: string | null;
          is_automated: boolean;
          sequence_step: "follow_up_1" | "follow_up_2" | null;
          outreach_message_id: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          prospect_id?: string | null;
          task_type: "first_outreach" | "follow_up" | "discovery_call" | "proposal_follow_up" | "qualification" | "internal_follow_up" | "handoff" | "other";
          title: string;
          due_date: string;
          due_time?: string | null;
          priority?: "low" | "medium" | "high" | "urgent";
          status?: "pending" | "completed" | "snoozed" | "cancelled";
          notes?: string | null;
          is_automated?: boolean;
          sequence_step?: "follow_up_1" | "follow_up_2" | null;
          outreach_message_id?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          prospect_id?: string | null;
          task_type?: "first_outreach" | "follow_up" | "discovery_call" | "proposal_follow_up" | "qualification" | "internal_follow_up" | "handoff" | "other";
          title?: string;
          due_date?: string;
          due_time?: string | null;
          priority?: "low" | "medium" | "high" | "urgent";
          status?: "pending" | "completed" | "snoozed" | "cancelled";
          notes?: string | null;
          is_automated?: boolean;
          sequence_step?: "follow_up_1" | "follow_up_2" | null;
          outreach_message_id?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_outreach_message_id_fkey";
            columns: ["outreach_message_id"];
            isOneToOne: false;
            referencedRelation: "outreach_messages";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_member: { Args: Record<PropertyKey, never>; Returns: boolean };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicTables = Database["public"]["Tables"];
export type Tables<T extends keyof PublicTables> = PublicTables[T]["Row"];
export type TablesInsert<T extends keyof PublicTables> = PublicTables[T]["Insert"];
export type TablesUpdate<T extends keyof PublicTables> = PublicTables[T]["Update"];
