"use client";

import { useState } from "react";
import { Database, Loader2, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ConfirmDialog } from "@/components/ui/dialog";
import { Input, NativeSelect } from "@/components/ui/input";
import { Field } from "@/components/ui/misc";
import { loadDemoDataAction, removeDemoDataAction, setUserRoleAction, updateProfileAction } from "@/lib/actions/settings";
import { useAction } from "@/lib/client/use-action";

export function ProfileForm({ fullName }: { fullName: string }) {
  const [name, setName] = useState(fullName);
  const { pending, run, fieldErrors } = useAction();
  return (
    <form
      className="flex flex-wrap items-end gap-2"
      onSubmit={(e) => {
        e.preventDefault();
        run(() => updateProfileAction({ full_name: name }), { success: "Profile saved" });
      }}
    >
      <Field label="Your name" htmlFor="full-name" hint="Shown as “Lead generated by” on handoffs." error={fieldErrors.full_name?.[0]} className="min-w-64 flex-1">
        <Input id="full-name" value={name} onChange={(e) => setName(e.target.value)} />
      </Field>
      <Button type="submit" disabled={pending}>
        Save
      </Button>
    </form>
  );
}

export function DemoDataControls({ hasDemo }: { hasDemo: boolean }) {
  const { pending, run } = useAction();
  return (
    <div className="flex flex-wrap gap-2">
      <Button
        disabled={pending || hasDemo}
        onClick={() => run(() => loadDemoDataAction(), { success: (d) => `Loaded ${d.prospects} demo prospects` })}
      >
        {pending ? <Loader2 className="animate-spin" /> : <Database />}
        Load demo data
      </Button>
      <ConfirmDialog
        trigger={
          <Button variant="outline" disabled={pending || !hasDemo}>
            <Trash2 /> Remove demo data
          </Button>
        }
        title="Remove all demo data?"
        description="Deletes every prospect marked Demo together with its messages, follow-ups, qualifications, opportunities, handoffs and activity. Your real prospects are not touched."
        confirmLabel="Remove demo data"
        destructive
        onConfirm={() => run(() => removeDemoDataAction(), { success: (d) => `Removed ${d.count} demo prospects` })}
      />
    </div>
  );
}

export function RoleSelect({ userId, role, disabled }: { userId: string; role: "admin" | "member" | "pending"; disabled?: boolean }) {
  const { pending, run } = useAction();
  return (
    <NativeSelect
      className="h-8 w-32 text-xs"
      value={role}
      disabled={disabled || pending}
      aria-label="Role"
      onChange={(e) => run(() => setUserRoleAction({ id: userId, role: e.target.value }), { success: "Role updated" })}
    >
      <option value="pending">Pending</option>
      <option value="member">Member</option>
      <option value="admin">Admin</option>
    </NativeSelect>
  );
}
