-- Reference data: BharatCoder services, project catalog, commission reference tiers
-- and the default outreach template library. This is NOT demo data — it ships with
-- the app and is editable in the UI. No prices are included on purpose: BharatCoder
-- has not provided official pricing.

-- services ------------------------------------------------------------------------
insert into public.services (slug, name, description, examples, sort_order) values
  ('web_development', 'Web Development',
   'Business-facing websites and web portals that generate enquiries and sales.',
   array['Business websites', 'Corporate websites', 'Landing pages', 'E-commerce', 'Web portals'], 1),
  ('custom_business_applications', 'Custom Business Applications',
   'Internal software that replaces spreadsheets, WhatsApp groups and manual processes.',
   array['CRM', 'Management systems', 'Admin dashboards', 'Internal tools', 'Workflow systems'], 2),
  ('ai_genai', 'AI / GenAI Solutions',
   'Practical AI features and assistants built into business workflows.',
   array['AI assistants', 'AI-powered workflows', 'Document processing', 'AI integrations', 'Custom GenAI applications'], 3),
  ('backend_api', 'Backend & API Development',
   'Robust server-side systems, databases and integrations.',
   array['REST APIs', 'Backend systems', 'Database systems', 'Third-party integrations', 'Authentication systems'], 4),
  ('lms_management', 'LMS & Management Systems',
   'Learning platforms and institute/organisation management portals.',
   array['Learning management systems', 'Student dashboards', 'Course platforms', 'Admin portals', 'Assessment systems'], 5);

-- project types -----------------------------------------------------------------
insert into public.project_types
  (slug, service_id, name, description, typical_client, typical_problem, potential_solution, discovery_questions, notes, sort_order)
values
  ('website', (select id from public.services where slug = 'web_development'), 'Business Website',
   'A professional, fast, mobile-friendly website with clear calls to action.',
   'Clinics, coaching institutes, professional-service firms, local businesses.',
   'No website, an outdated website, or a site that does not generate enquiries.',
   'Modern website with enquiry forms, WhatsApp click-to-chat, Google Maps and basic SEO structure.',
   array['What should a visitor do on the website (call, book, enquire, buy)?', 'How do enquiries reach you today?', 'Who will update content after launch?', 'Do you have brand assets (logo, photos, copy)?', 'Which competitor websites do you like?'],
   null, 1),
  ('ecommerce', (select id from public.services where slug = 'web_development'), 'E-commerce Store',
   'Online store with catalogue, cart, payments, order and inventory management.',
   'D2C brands, retailers moving online, Instagram sellers.',
   'Orders taken manually over Instagram/WhatsApp; no checkout; inventory tracked by hand.',
   'E-commerce site with payment gateway, order dashboard, shipping and inventory integration.',
   array['How many products/SKUs?', 'How are orders and payments handled today?', 'Which payment gateway and shipping partners?', 'Monthly order volume?', 'Do you need COD, coupons, GST invoices?'],
   'Payment gateway fees, hosting and paid plugins are pass-through costs.', 2),
  ('web_application', (select id from public.services where slug = 'custom_business_applications'), 'Web Application',
   'Custom browser-based application built around a specific business workflow.',
   'Growing SMEs, operations-heavy businesses, startups.',
   'Critical work runs on spreadsheets, paper or disconnected tools.',
   'Role-based web app with forms, workflows, dashboards and reports.',
   array['Walk me through the workflow step by step.', 'Who are the users and what can each role do?', 'What data do you track today and where?', 'Which reports do managers need?', 'Which tools must it integrate with?'],
   null, 3),
  ('saas', (select id from public.services where slug = 'custom_business_applications'), 'SaaS Product',
   'Multi-tenant software product sold on subscription.',
   'Startups and founders with a validated product idea.',
   'Idea or MVP needs production-grade build, billing and multi-tenancy.',
   'MVP scoped to core features, tenant management, subscription billing and admin panel.',
   array['Who is the customer and what job does the product do?', 'Is there an existing MVP, design or prototype?', 'What must be in version 1 vs later?', 'How will you charge customers?', 'Funding stage and launch deadline?'],
   null, 4),
  ('crm', (select id from public.services where slug = 'custom_business_applications'), 'CRM / Lead Management',
   'Lead, customer and follow-up management tailored to the sales process.',
   'Agencies, real-estate firms, education counsellors, service businesses.',
   'Leads managed in spreadsheets or WhatsApp; follow-ups missed; no visibility.',
   'CRM with lead capture, pipeline stages, follow-up reminders, assignments and reports.',
   array['Where do leads come from today?', 'How many leads per month and how many salespeople?', 'What are your sales stages?', 'What gets missed today?', 'Do you already pay for a CRM? Why is it not working?'],
   null, 5),
  ('erp', (select id from public.services where slug = 'custom_business_applications'), 'ERP / Operations System',
   'Integrated management of operations: inventory, purchase, billing, HR or production.',
   'Manufacturers, distributors, multi-branch businesses.',
   'Departments run on separate spreadsheets; data is inconsistent and slow.',
   'Modular operations system covering the highest-pain departments first.',
   array['Which departments and processes are in scope?', 'What software is used today?', 'How many users and branches?', 'Which reports are critical?', 'Accounting/Tally or GST integration needed?'],
   'Usually large scope — recommend phased delivery.', 6),
  ('lms', (select id from public.services where slug = 'lms_management'), 'LMS / Course Platform',
   'Platform to deliver courses, track students and run assessments.',
   'Coaching institutes, trainers, schools, corporate training teams.',
   'Course material shared via WhatsApp/Drive; no tracking of progress or fees.',
   'LMS with student portal, course content, assessments, progress tracking, payments and admin portal.',
   array['How do you deliver material today?', 'How many students and batches?', 'Live classes, recorded videos or both?', 'Do you need tests, certificates, fee collection?', 'Mobile access requirements?'],
   null, 7),
  ('dashboard', (select id from public.services where slug = 'custom_business_applications'), 'Admin Dashboard / Reporting',
   'Dashboards and admin panels that consolidate business data.',
   'Businesses with data in multiple tools; agencies reporting to clients.',
   'Owners cannot see key numbers without manual spreadsheet work.',
   'Admin dashboard with KPIs, filters, exports and scheduled reports.',
   array['Which numbers do you check every week?', 'Where does that data live?', 'Who needs access?', 'How fresh must the data be?'],
   null, 8),
  ('ai_genai', (select id from public.services where slug = 'ai_genai'), 'AI / GenAI Solution',
   'AI assistants, document processing and AI-powered workflows.',
   'Businesses with repetitive text/document work or support volume.',
   'Staff spend hours on repetitive answers, data entry or document review.',
   'AI assistant or workflow integrated with existing data, with human review where needed.',
   array['Which repetitive task costs the most time?', 'What documents/data would the AI use?', 'What accuracy is acceptable and who reviews output?', 'Any data privacy constraints?', 'Which systems should it connect to?'],
   'Paid AI API usage is a pass-through cost.', 9),
  ('api_backend', (select id from public.services where slug = 'backend_api'), 'API / Backend Development',
   'APIs, backend services, databases and third-party integrations.',
   'Startups, agencies with front-end teams, businesses integrating tools.',
   'Systems do not talk to each other; slow or unreliable backend.',
   'Well-documented REST APIs, database design, authentication and integrations.',
   array['Which systems need to connect?', 'Expected traffic/volume?', 'Existing stack and hosting?', 'Who consumes the API?', 'Security/compliance requirements?'],
   null, 10),
  ('automation', (select id from public.services where slug = 'custom_business_applications'), 'Workflow Automation',
   'Automating repetitive business processes and notifications.',
   'Operations teams, agencies, service businesses.',
   'Manual copy-paste between tools, missed reminders, repetitive admin.',
   'Automated workflows, reminders and integrations between existing tools.',
   array['Which task is repeated most often?', 'Which tools are involved?', 'What triggers the task?', 'What happens when it is missed?'],
   null, 11),
  ('mobile_application', (select id from public.services where slug = 'custom_business_applications'), 'Mobile Application',
   'Mobile app for customers or field staff.',
   'Consumer businesses, field-service teams, startups.',
   'Customers or staff need on-the-go access the website cannot provide.',
   'Mobile app (or mobile-first web app) connected to a shared backend.',
   array['Customer-facing or internal?', 'Android, iOS or both?', 'Which features must work offline?', 'Is a mobile-friendly web app enough?'],
   'Confirm with BharatCoder that mobile apps are in scope before pitching.', 12),
  ('custom_software', (select id from public.services where slug = 'custom_business_applications'), 'Custom Software',
   'Bespoke software that does not fit a standard category.',
   'Any business with a unique process.',
   'Off-the-shelf tools do not fit the way the business works.',
   'Scoped custom build — start with discovery and a phased plan.',
   array['What does success look like in 6 months?', 'What have you already tried?', 'Who will use it daily?', 'Budget range and deadline?'],
   null, 13);

-- commission reference tiers --------------------------------------------------------
-- Ranges are [min, max). Below ₹25K there is no default tier (negotiate separately).
insert into public.commission_settings (tier_name, min_amount, max_amount, percentage, sort_order, notes) values
  ('Small',  25000,  100000, 12, 1, '₹25K–₹1L project'),
  ('Medium', 100000, 500000, 10, 2, '₹1L–₹5L project'),
  ('Large',  500000, null,    7, 3, '₹5L+ project');

-- default outreach templates ----------------------------------------------------------
insert into public.outreach_templates (name, channel, audience, outreach_stage, subject, body, is_generic, created_by) values
  ('Agency Partnership — First Contact', 'email', 'marketing_agency', 'first_contact',
   'Potential Development Partnership',
   E'Hi {{first_name}},\n\nI came across {{company_name}} and noticed that your team works with businesses on {{service_area}}.\n\nI’m working with BharatCoder.com, a development team handling websites, custom web applications, AI solutions, APIs and business management systems.\n\nWe’re currently looking to partner with agencies that may occasionally need a reliable technical development partner or white-label development support.\n\nYour team could continue handling the client relationship while BharatCoder handles the technical development and delivery.\n\nWould you be open to discussing a potential development partnership?\n\nBest,\nUtkarsh',
   true, null),
  ('Direct Business — First Contact', 'email', 'direct_business', 'first_contact',
   'Quick idea for {{company_name}}',
   E'Hi {{first_name}},\n\nI came across {{company_name}} and noticed {{personalized_observation}}.\n\nI work with BharatCoder.com, a software development team that builds websites, custom business applications and digital systems.\n\nI noticed {{specific_problem}} and had an idea for how this could potentially be improved.\n\nWould you be open to a quick conversation?\n\nBest,\nUtkarsh',
   true, null),
  ('Agency Follow-up #1', 'email', 'marketing_agency', 'follow_up_1',
   'Re: Potential Development Partnership',
   E'Hi {{first_name}},\n\nJust following up on my previous message regarding development support for {{company_name}}.\n\nIf your team ever has clients who need websites, web applications, dashboards, APIs or custom software, we''d be happy to explore supporting the technical side.\n\nHappy to share more details if useful.\n\nBest,\nUtkarsh',
   false, null),
  ('Agency Follow-up #2', 'email', 'marketing_agency', 'follow_up_2',
   'Re: Potential Development Partnership',
   E'Hi {{first_name}},\n\nJust closing the loop here.\n\nIf development isn''t something your team currently needs support with, no worries.\n\nIf you do have upcoming projects requiring technical development, I''d be happy to connect.\n\nBest,\nUtkarsh',
   false, null),
  ('Agency Partnership — LinkedIn Connection Note', 'linkedin', 'marketing_agency', 'first_contact', null,
   E'Hi {{first_name}}, I came across {{company_name}}’s work on {{service_area}}. I work with BharatCoder.com — we act as a white-label development partner for agencies (websites, web apps, APIs, AI). Would be glad to connect.',
   true, null),
  ('SEO Agency — First Contact', 'email', 'seo_agency', 'first_contact',
   'Development support for your SEO clients',
   E'Hi {{first_name}},\n\nI came across {{company_name}} and noticed {{personalized_observation}}.\n\nSEO clients often need site rebuilds, speed fixes or new landing pages before rankings can improve. I work with BharatCoder.com, a development team that could handle that technical work white-label, while your team keeps the client relationship.\n\nWould it be worth a short conversation to see if there is a fit?\n\nBest,\nUtkarsh',
   true, null),
  ('Social Media Agency — Instagram DM', 'instagram', 'social_media_agency', 'first_contact', null,
   E'Hi {{first_name}}! Loved {{personalized_observation}}. I work with BharatCoder.com — we build websites, landing pages and web apps for agencies'' clients (white-label). If your clients ever need development support, happy to chat.',
   true, null),
  ('Direct Business — WhatsApp First Contact', 'whatsapp', 'direct_business', 'first_contact', null,
   E'Hi {{first_name}}, this is Utkarsh from BharatCoder.com. I came across {{company_name}} and noticed {{specific_problem}}. We help businesses fix this with {{potential_solution}}. Would you be open to a quick 10-minute call this week?',
   true, null),
  ('Healthcare — First Contact', 'email', 'healthcare', 'first_contact',
   'Online bookings for {{company_name}}',
   E'Hi {{first_name}},\n\nI came across {{company_name}} and noticed {{personalized_observation}}.\n\nMany clinics lose appointments when patients can''t book online or get a quick reply. I work with BharatCoder.com — we build clinic websites with appointment booking and enquiry management.\n\nWould you be open to a quick conversation about {{specific_problem}}?\n\nBest,\nUtkarsh',
   true, null),
  ('Education — First Contact', 'email', 'education', 'first_contact',
   'Student portal idea for {{company_name}}',
   E'Hi {{first_name}},\n\nI came across {{company_name}} and noticed {{personalized_observation}}.\n\nI work with BharatCoder.com — we build learning platforms and student portals so course material, tests and fee tracking live in one place instead of WhatsApp groups.\n\nWould you be open to a short call to see if this could help?\n\nBest,\nUtkarsh',
   true, null),
  ('Direct Business — Follow-up #1', 'email', 'direct_business', 'follow_up_1',
   'Re: Quick idea for {{company_name}}',
   E'Hi {{first_name}},\n\nJust following up on my earlier note about {{specific_problem}}.\n\nHappy to share a couple of examples of how similar businesses solved this — no obligation.\n\nBest,\nUtkarsh',
   false, null),
  ('Direct Business — Follow-up #2', 'email', 'direct_business', 'follow_up_2',
   'Re: Quick idea for {{company_name}}',
   E'Hi {{first_name}},\n\nClosing the loop on my previous messages. If now isn''t the right time, no problem at all.\n\nIf {{specific_problem}} becomes a priority later, I''d be glad to help.\n\nBest,\nUtkarsh',
   false, null),
  ('Interested Response', 'email', 'general', 'interested_response',
   'Re: next steps',
   E'Hi {{first_name}},\n\nThanks for getting back to me — great to hear this is relevant.\n\nTo make the most of a call, could you share a little about what you''re currently using and what isn''t working? Then I can bring the right person from the BharatCoder team.\n\nWhat time works for a 20-minute call this week?\n\nBest,\nUtkarsh',
   false, null),
  ('Discovery Call Invitation', 'email', 'general', 'discovery_call_invitation',
   'Discovery call — {{company_name}} × BharatCoder',
   E'Hi {{first_name}},\n\nWould you be available for a 20–30 minute discovery call to understand your requirements for {{project_type}}?\n\nWe''ll cover:\n- What you''re trying to achieve\n- How things work today\n- Timeline and budget expectations\n\nPlease share a couple of time slots that work for you.\n\nBest,\nUtkarsh',
   false, null),
  ('Post-Call Follow-up', 'email', 'general', 'post_call_follow_up',
   'Thanks for the call — next steps',
   E'Hi {{first_name}},\n\nThanks for your time today. Summary of what we discussed:\n- Problem: {{specific_problem}}\n- Possible solution: {{potential_solution}}\n\nNext step: the BharatCoder technical team will review the requirements and follow up with questions/scope.\n\nBest,\nUtkarsh',
   false, null),
  ('Proposal Follow-up', 'email', 'general', 'proposal_follow_up',
   'Re: Proposal for {{company_name}}',
   E'Hi {{first_name}},\n\nJust checking whether you had a chance to review the proposal for {{project_type}}.\n\nHappy to set up a quick call with the BharatCoder team to answer any questions.\n\nBest,\nUtkarsh',
   false, null),
  ('Re-engagement', 'email', 'general', 're_engagement',
   'Checking in — {{company_name}}',
   E'Hi {{first_name}},\n\nWe spoke a while ago about {{specific_problem}}. Checking in to see whether this is back on your radar.\n\nIf it is, I''d be happy to reconnect.\n\nBest,\nUtkarsh',
   false, null);
