import { describe, expect, it } from "vitest";
import { generateHandoff, urgencyLabel, type HandoffProspect, type HandoffQualification } from "@/lib/domain/handoff";
import { escapeCsvCell, toCsv } from "@/lib/domain/csv";
import { InvalidMoneyError, formatBudgetRange, formatINRCompact, parseMoney, sumMoney } from "@/lib/domain/money";
import { commissionOnReceived, commissionOutstanding, InvalidCommissionError, referenceTier } from "@/lib/domain/commission";
import { addDays, dueBucket, isIsoDate, startOfWeek, todayInTimezone } from "@/lib/domain/dates";
import { acquisitionRates, funnelCounts, furthestStage, rate } from "@/lib/domain/metrics";
import { recommendServices } from "@/lib/domain/service-mapping";

const prospect: HandoffProspect = {
  business_name: "ABC Physiotherapy",
  contact_name: "John Doe",
  job_title: "Founder",
  email: "john@abcphysio.in",
  phone: "+91 98765 43210",
  whatsapp: "+91 98765 43210",
  website: "https://abcphysio.in",
  location: "Pune",
  country: "India",
  industry: "Healthcare",
  prospect_type: "direct_business",
  lead_source: "instagram",
  source_url: null,
  observed_problem: "Current website does not support online appointment booking.",
  suggested_solution: "New website + appointment booking + enquiry management.",
  potential_project: "website",
  estimated_value: "150000.00",
  recommended_services: [],
};

const qualification: HandoffQualification = {
  business_model: "Clinic",
  current_technology: "WordPress site",
  problem_description: null,
  current_solution: "Phone bookings",
  whats_not_working: null,
  cost_of_inaction: null,
  project_type: "website",
  required_features: "Booking, enquiries",
  integrations: null,
  number_of_users: null,
  estimated_complexity: "medium",
  desired_launch_date: null,
  timeline_notes: "4–6 weeks",
  budget_min: "100000.00",
  budget_max: "200000.00",
  budget_notes: null,
  decision_maker_identified: true,
  decision_maker_name: "Founder",
  decision_process: null,
  other_stakeholders: null,
  urgency: 4,
  score: 75,
  classification: "qualified",
  notes: "Client is interested in discussing requirements this week.",
};

describe("handoff generation", () => {
  it("produces the handoff summary with all key sections", () => {
    const { markdown, snapshot, gaps } = generateHandoff({
      prospect,
      qualification,
      generatedBy: "Utkarsh",
      generatedOn: "2026-09-28",
    });
    expect(markdown.startsWith("## BharatCoder Lead Handoff")).toBe(true);
    expect(snapshot.Client).toBe("ABC Physiotherapy");
    expect(snapshot.Contact).toContain("John Doe (Founder)");
    expect(snapshot.Contact).not.toContain("WhatsApp"); // same as phone
    expect(snapshot.Problem).toContain("online appointment booking");
    expect(snapshot.Budget).toBe("₹1L–2L");
    expect(snapshot.Timeline).toBe("4–6 weeks");
    expect(snapshot["Decision maker"]).toBe("Founder");
    expect(snapshot.Urgency).toBe("High (4/5)");
    expect(snapshot.Source).toBe("Instagram");
    expect(snapshot["Lead generated by"]).toBe("Utkarsh");
    expect(snapshot.Notes).toContain("this week");
    expect(gaps).toEqual([]);
  });

  it("lists gaps when information is missing", () => {
    const { gaps, snapshot, markdown } = generateHandoff({
      prospect: { ...prospect, contact_name: null, email: null, phone: null, whatsapp: null, observed_problem: null, estimated_value: null },
      qualification: null,
      generatedBy: "",
      generatedOn: "2026-09-28",
    });
    expect(gaps).toEqual(
      expect.arrayContaining(["Contact person", "Direct contact details (email/phone)", "Problem statement", "Budget range", "Timeline", "Qualification assessment"]),
    );
    expect(snapshot.Budget).toBe("Not discussed");
    expect(markdown).toContain("**Still to confirm:**");
  });

  it("labels urgency", () => {
    expect(urgencyLabel(5)).toBe("High");
    expect(urgencyLabel(3)).toBe("Medium");
    expect(urgencyLabel(1)).toBe("Low");
    expect(urgencyLabel(null)).toBe("Unknown");
  });
});

describe("CSV export", () => {
  it("escapes quotes, commas and newlines", () => {
    expect(escapeCsvCell('He said "hi", ok')).toBe('"He said ""hi"", ok"');
    expect(escapeCsvCell("line1\nline2")).toBe('"line1\nline2"');
    expect(escapeCsvCell(null)).toBe("");
    expect(escapeCsvCell(undefined)).toBe("");
    expect(escapeCsvCell(42)).toBe("42");
    expect(escapeCsvCell(-5)).toBe("-5");
  });

  it("neutralises spreadsheet formulas in text", () => {
    expect(escapeCsvCell("=HYPERLINK(\"x\")")).toBe("\"'=HYPERLINK(\"\"x\"\")\"");
    expect(escapeCsvCell("+91 98765")).toBe("'+91 98765");
    expect(escapeCsvCell("@user")).toBe("'@user");
  });

  it("builds a CSV document with header row", () => {
    const csv = toCsv([{ a: "x", b: 1 }, { a: "y,z", b: null }], [
      { header: "A", value: (r) => r.a },
      { header: "B", value: (r) => r.b },
    ]);
    expect(csv).toBe('﻿A,B\r\nx,1\r\n"y,z",\r\n');
    expect(toCsv([], [{ header: "Only", value: () => "" }])).toBe("﻿Only\r\n");
  });
});

describe("money", () => {
  it("parses Indian formats exactly", () => {
    expect(parseMoney("150000")).toBe("150000.00");
    expect(parseMoney("1,50,000")).toBe("150000.00");
    expect(parseMoney("₹1.5L")).toBe("150000.00");
    expect(parseMoney("2 lakh")).toBe("200000.00");
    expect(parseMoney("75k")).toBe("75000.00");
    expect(parseMoney("1.2cr")).toBe("12000000.00");
    expect(parseMoney("0.1")).toBe("0.10");
    expect(parseMoney("19.999")).toBe("20.00");
    expect(parseMoney("")).toBeNull();
    expect(parseMoney(null)).toBeNull();
  });

  it("rejects invalid or negative amounts", () => {
    for (const bad of ["-100", "abc", "1.2.3", "5x", "1e5", "999999999999999"]) {
      expect(() => parseMoney(bad), bad).toThrow(InvalidMoneyError);
    }
  });

  it("formats compact and ranges", () => {
    expect(formatINRCompact("150000.00")).toBe("₹1.5L");
    expect(formatINRCompact(75000)).toBe("₹75K");
    expect(formatINRCompact(null)).toBe("—");
    expect(formatBudgetRange(null, null)).toBe("Not discussed");
    expect(formatBudgetRange(100000, null)).toBe("₹1L+");
    expect(formatBudgetRange(null, 50000)).toBe("Up to ₹50K");
  });

  it("sums without floating point drift", () => {
    expect(sumMoney(["0.10", "0.20", null, "abc"])).toBe(0.3);
  });
});

describe("commission reference", () => {
  it("finds reference tiers with [min, max) boundaries", () => {
    expect(referenceTier(24999)).toBeNull();
    expect(referenceTier(25000)?.percentage).toBe(12);
    expect(referenceTier(99999.99)?.percentage).toBe(12);
    expect(referenceTier(100000)?.percentage).toBe(10);
    expect(referenceTier(500000)?.percentage).toBe(7);
    expect(referenceTier(null)).toBeNull();
    expect(referenceTier(-1)).toBeNull();
  });

  it("calculates commission on received amount with the AGREED percentage", () => {
    expect(commissionOnReceived("150000.00", "10")).toBe(15000);
    expect(commissionOnReceived("33333.33", "12.5")).toBe(4166.67);
    expect(commissionOnReceived(null, 10)).toBe(0);
    expect(commissionOnReceived(100000, null)).toBeNull(); // never guessed from tiers
    expect(() => commissionOnReceived(-1, 10)).toThrow(InvalidCommissionError);
    expect(() => commissionOnReceived(100, 101)).toThrow(InvalidCommissionError);
  });

  it("computes outstanding commission", () => {
    expect(commissionOutstanding(15000, "5000")).toBe(10000);
    expect(commissionOutstanding(15000, "20000")).toBe(0);
    expect(commissionOutstanding(null, 0)).toBeNull();
  });
});

describe("dates", () => {
  it("computes today in the business timezone", () => {
    // 20:00 UTC on 28 Sep is already 29 Sep in India
    expect(todayInTimezone("Asia/Kolkata", new Date("2026-09-28T20:00:00Z"))).toBe("2026-09-29");
    expect(todayInTimezone("UTC", new Date("2026-09-28T20:00:00Z"))).toBe("2026-09-28");
  });

  it("adds days, validates and buckets", () => {
    expect(addDays("2026-02-27", 2)).toBe("2026-03-01");
    expect(() => addDays("2026-02-30", 1)).toThrow();
    expect(isIsoDate("2026-02-30")).toBe(false);
    expect(isIsoDate("2026-09-28")).toBe(true);
    expect(dueBucket("2026-09-27", "2026-09-28")).toBe("overdue");
    expect(dueBucket("2026-09-28", "2026-09-28")).toBe("today");
    expect(dueBucket("2026-09-29", "2026-09-28")).toBe("upcoming");
    expect(startOfWeek("2026-09-27")).toBe("2026-09-21"); // Sunday → Monday before
  });
});

describe("metrics", () => {
  it("counts funnel progress cumulatively, including lost prospects", () => {
    const c = funnelCounts([
      { stage: "prospect" },
      { stage: "contacted" },
      { stage: "replied" },
      { stage: "qualified" },
      { stage: "won" },
      { stage: "lost", reachedStage: "replied" },
    ]);
    expect(c).toMatchObject({ total: 6, contacted: 5, replied: 4, qualified: 2, opportunities: 1, won: 1, lost: 1 });
    const r = acquisitionRates(c);
    expect(r.contactRate).toBe(83.3);
    expect(r.responseRate).toBe(80);
    expect(r.qualificationRate).toBe(50);
  });

  it("returns null rates for empty data", () => {
    expect(rate(0, 0)).toBeNull();
    expect(acquisitionRates(funnelCounts([])).contactRate).toBeNull();
  });

  it("finds furthest stage", () => {
    expect(furthestStage("lost", ["contacted", "replied", "lost"])).toBe("replied");
    expect(furthestStage("qualified", [])).toBe("qualified");
  });
});

describe("service mapping", () => {
  it("maps WhatsApp course material to LMS", () => {
    const [top] = recommendServices("Students currently receive course material through WhatsApp.");
    expect(top.rule.id).toBe("course-material-whatsapp");
    expect(top.rule.solutions).toContain("LMS");
  });

  it("maps spreadsheet lead management to CRM", () => {
    const [top] = recommendServices("Staff manually manage leads using spreadsheets");
    expect(top.rule.solutions).toContain("CRM");
  });

  it("returns nothing for empty text", () => {
    expect(recommendServices("")).toEqual([]);
    expect(recommendServices(null)).toEqual([]);
  });
});
